import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import ProductList from "@/components/ProductList";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { subCategory } = router.query;

  return (
    <>
      <Head>
        <title>LatinAmerica Business Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row">
        <div className="col-md-3">
          <Sidebar />
        </div>
        <div className="col-md-8 my-5">
          <div style={{ margin: "40px 0px", maxWidth: "500px" }}>
            <input
              type="text"
              name=""
              className="form-control"
              id=""
              placeholder="Search Product"
            />
          </div>
          <p>CATEGORY: {subCategory?.toUpperCase()}</p>
          <hr style={{ border: "2px solid white", opacity: 1 }} />
          <ProductList subCategory={subCategory} />
        </div>
      </div>
    </>
  );
}
