import Head from "next/head";
import Link from "next/link";
import { Searchbar } from "@/components/Searchbar";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Catalogo de productos LBC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        style={{
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <img src="/img/logo/logo.png" alt="" width={300} />
        <div>
          <h3>Find products from latinamerica</h3>
          <div>
            <Searchbar />
          </div>
        </div>
      </section>
      <section
        style={{
          marginTop: "100px",
          display: "flex",
          justifyItems: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        <h3 className="my-5">BEST SELLING PRODUCTS</h3>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: "40px",
          }}
        >
          <Link href="/productos/coffee">
            <img src="/img/cafe/COFFEE.png" alt="" width={300} />
          </Link>
          <Link href="/productos/vegetables">
            <img src="/img/cafe/VEGETABLES.png" alt="" width={300} />
          </Link>
          <Link href="/productos/swimsuits">
            <img src="/img/cafe/SWIMSUITS.png" alt="" width={300} />
          </Link>
          {/* <div>
            <img src="/img/Inicio/3.png" alt="" width={300} />
          </div>
          <div>
            <img src="/img/Inicio/4.png" alt="" width={300} />
          </div> */}
        </div>
      </section>
    </div>
  );
};

export default Index;
