import { useCallback, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const Index = () => {
  const [searchedProduct, setSearchedProduct] = useState("")
  const router = useRouter()

  const handleSearch = useCallback((e, query = "") => {
    e.preventDefault()
    if(!query) return

    router.push(`/buscador?q=${query}`)
  }, [router])

  return (
    <div>
      <Head>
        <title>Catalogo de productos LBC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        style={{
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <img src="/img/logo/logo.png" alt="" width={300} />
        <div>
          <h3>Find products from latinamerica</h3>
          <div>
            <form 
              onSubmit={ e => handleSearch(e, searchedProduct) }
              style={{
                display: "flex",
                justifyContent: "center",
                alignContent: "center",
              }}
            >
              <input
                style={{
                  width: "80%",
                  marginRight: "20px",
                  borderRadius: "10px",
                }}
                type="text"
                name=""
                id=""
                value={ searchedProduct }
                onChange={ (e) => setSearchedProduct(e.target.value) }
              />
              <button
                style={{
                  background: "#B9A46D",
                  padding: "7px 15px",
                  border: "none",
                  borderRadius: "10px",
                  color: "white",
                }}
                type="submit"
              >
                Search
              </button>
            </form>
          </div>
        </div>
      </section>
      <section
        style={{
          marginTop: "100px",
          display: "flex",
          justifyItems: "center",
          alignItems: "center",
          flexDirection: "column",
        }}
      >
        <h3 className="my-5">BEST SELLING PRODUCTS</h3>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: "40px",
          }}
        >
          <Link href="/productos/coffee">
            <img src="/img/cafe/COFFEE.png" alt="" width={300} />
          </Link>
          <Link href="/productos/vegetables">
            <img src="/img/cafe/VEGETABLES.png" alt="" width={300} />
          </Link>
          <Link href="/productos/swimsuits">
            <img src="/img/cafe/SWIMSUITS.png" alt="" width={300} />
          </Link>
          {/* <div>
            <img src="/img/Inicio/3.png" alt="" width={300} />
          </div>
          <div>
            <img src="/img/Inicio/4.png" alt="" width={300} />
          </div> */}
        </div>
      </section>
    </div>
  );
};

export default Index;
